version: '3'

services:
  flask-app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      FLASK_ENV: development
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: vidyo
